"""add upload processing fields and order items table

Revision ID: 0af8505c42c3
Revises: 420e360b0aa9
Create Date: 2026-08-05 14:49:31.723789

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "0af8505c42c3"
down_revision: str | None = "420e360b0aa9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("upload_id", sa.Uuid(), nullable=False),
        sa.Column(
            "marketplace",
            sa.Enum(
                "shopee",
                "mercado_livre",
                "amazon",
                "magalu",
                name="order_item_marketplace",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("external_order_id", sa.String(length=255), nullable=False),
        sa.Column("sku", sa.String(length=255), nullable=False),
        sa.Column("product_name", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_cents", sa.Integer(), nullable=False),
        sa.Column("total_price_cents", sa.Integer(), nullable=False),
        sa.Column("discount_percentage", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "completed",
                "pending",
                "cancelled",
                "refunded",
                "unknown",
                name="order_item_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["uploads.id"],
            name=op.f("fk_order_items_upload_id_uploads"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_order_items_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index(
        op.f("ix_order_items_external_order_id"), "order_items", ["external_order_id"], unique=False
    )
    op.create_index(op.f("ix_order_items_order_date"), "order_items", ["order_date"], unique=False)
    op.create_index(op.f("ix_order_items_sku"), "order_items", ["sku"], unique=False)
    op.create_index(op.f("ix_order_items_upload_id"), "order_items", ["upload_id"], unique=False)
    op.create_index(op.f("ix_order_items_user_id"), "order_items", ["user_id"], unique=False)
    op.add_column("uploads", sa.Column("started_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("uploads", sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("uploads", "finished_at")
    op.drop_column("uploads", "started_at")
    op.drop_index(op.f("ix_order_items_user_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_upload_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_sku"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_order_date"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_external_order_id"), table_name="order_items")
    op.drop_table("order_items")
    # ### end Alembic commands ###
